info:
  contact: {}
  description: This is a sample server Petstore server.
  license: {}
  title: Swagger Example API
  version: "1.0"
paths:
  /btc/wallet/accounts/:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 钱包的Id
        in: formData
        name: walletid
        required: true
        type: integer
      - description: BTC地址
        in: formData
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: 添加BTC帐户成功
          schema:
            type: string
        "400":
          description: 非法参数
          schema:
            type: string
        "500":
          description: 失败
          schema:
            type: string
      summary: 向钱包增加BTC帐户
  /btc/wallet/phone/:
    put:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 钱包的Id
        in: formData
        name: walletid
        required: true
        type: integer
      - description: 电话号码
        in: formData
        name: phone
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 修改电话号码成功
          schema:
            type: string
        "400":
          description: 非法参数
          schema:
            type: string
        "500":
          description: 失败
          schema:
            type: string
      summary: 修改钱包的电话号码
  /bth/balance/:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 比特币帐户地址
        in: formData
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: failed
          schema:
            type: string
        "500":
          description: failed
          schema:
            type: string
      summary: 获取余额(比特币)
swagger: "2.0"
