basePath: '{{.BasePath}}'
host: '{{.Host}}'
info:
  contact: {}
  description: This is a sample server Petstore server.
  license: {}
  title: Swagger Example API
  version: "1.0"
paths:
  /bth/balance/:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 比特币帐户地址
        in: formData
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: failed
          schema:
            type: string
        "500":
          description: failed
          schema:
            type: string
      summary: 获取余额(比特币)
swagger: "2.0"
